# Generated by Django 6.1.1 on 2026-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
